before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: L5UFP5Lp7xtFljkbxDBNSs85iszAAQa4svQbKoo8p+k+VRLH96SgXb1kf4bjY2qfU+Q12AoYoCMgTbdcbki09aWme6bgbYkcD9WHtMKe3WJRWlNiJ6Pv/0bimXmNWUk+GXgvngeudRYTrDHIUCWUHXnTDr4UZqL1f7yE44+9iyR/5H/kNjZCaf0w0h/rHbPcjNaWW6lMdaEU9atv12WSiOnc0kPYIrqyf0P/HHTfCH9tN6HsL1Xj/1+4YHqdRZHJWWm9Hi+Bu7kzV/g2062GvfpgYGIWIsK5ov8xnkR83E/Ri2JBUPPrq9BOV0qTppqMhPki2G1XW44FFs73lH/7NQLjo2Uw2WNIAUYYwI5qbPBPTEp3y96M2yyCey3OhCGfchvnHBH2gZQxaBL0ii5s+o7Es17HIvYher/V90Rn0osrMmTFeSHU31UOKERQwHdGxcdwJJqtV9P8b/ymYIFMKK05Q1/rcgcmVgSkQG19W8rZL+LdbxdHPuzQFrcbd/TBztS3Lj1AEeF5rJuEapNvqGDQv3pLMCFLXiOBrftT/bP3AI7v/10+9au2WlylxEsuCll+BMEnfF9Ji9hr2viV3D3uHTs1i60y6oi+GncD/E4MmDZe3DubSq0OVZRgXY2Q8rRJKCtPCrQ1Km6aYdI+8x2ijRg66IZtvXQixD7W3I4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
